export default function Brosfood() {
    return (
        <>

            <p>Hola</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse soluta dolorem molestiae necessitatibus, architecto ipsum accusamus ducimus praesentium, officiis cumque quaerat velit repellat at ea minus quod quibusdam, ullam qui?
                Neque rem enim doloribus sunt quam nihil cupiditate inventore praesentium asperiores? Aperiam quidem aliquid quisquam possimus officiis expedita commodi, eos accusamus natus esse autem reiciendis eaque veniam nobis laboriosam eveniet.
                Laborum ullam magni cumque corporis maiores magnam placeat et distinctio necessitatibus, aperiam molestiae unde sunt aliquam voluptatum ipsa illo iure obcaecati quos mollitia, fuga quae, dolorum quisquam in? Voluptates, nam.
                Odio, porro fugit eveniet error obcaecati commodi nihil, officiis at amet quod tenetur ipsum! Maiores quidem dolorum voluptate nisi, amet quo ab, provident illum praesentium cumque perferendis consequatur? Ipsam, ea.
                Quae in libero maxime eaque et quod incidunt suscipit illum consequatur provident amet numquam atque molestias voluptas fugiat architecto nostrum quia qui laboriosam fuga, placeat id voluptatibus mollitia dolorem? Veritatis!
                Molestias cum quisquam tempora provident aliquam perspiciatis natus totam minus quaerat iusto voluptatibus vero dolorem recusandae officia distinctio labore harum reiciendis debitis nostrum, maxime maiores! Magni quisquam voluptate alias dolore.
                Porro, tenetur. Dicta dolores ab ullam eveniet quas magnam unde nihil fugiat numquam harum natus iure, provident architecto iusto saepe facilis nemo illum doloribus quos optio voluptate molestias reprehenderit? Minima?
                Adipisci sed repellendus iure neque architecto, quibusdam tempore, blanditiis vitae ut fuga eum laudantium labore expedita voluptatem beatae necessitatibus exercitationem magni molestias id, sit ea eligendi ex saepe? Eum, odit!
                Nulla laborum voluptatem voluptas unde aut vel, quas magni praesentium impedit fugit exercitationem placeat magnam? Commodi architecto eum maxime aperiam adipisci similique sit, tenetur dolore illum illo odio recusandae neque!
                Velit sequi, excepturi minima odit eum id, illum cupiditate voluptate impedit molestias praesentium officia nesciunt porro eaque obcaecati delectus. Unde atque quos quasi vero alias repudiandae beatae architecto non voluptas?
                Deserunt doloribus fugiat quo quod neque eum tempora iure perspiciatis nemo rem nam unde corrupti ex, et tenetur tempore nisi ipsa quisquam magnam, ad totam eligendi. Asperiores soluta labore corrupti!
                Perferendis quod unde error rem nisi eius, accusamus eos porro temporibus et quam laudantium nihil possimus, ipsam, distinctio deleniti? Tempore odio ratione cupiditate accusantium ea reiciendis obcaecati velit cum delectus.
                Consectetur itaque delectus nostrum reprehenderit ipsam veritatis autem expedita repellendus doloribus inventore, neque aliquid porro? Neque aliquam cum reprehenderit totam vero voluptate labore corrupti voluptatem! Laboriosam quae dolorem nobis commodi?
                Voluptatum officia modi libero accusamus amet praesentium, facilis reprehenderit doloribus enim eius, voluptatibus hic alias repellat magni molestiae repellendus itaque corporis aspernatur ut ipsum officiis provident. Ratione ipsum quam et!
                Accusantium delectus ut dolores voluptates minima magni laborum at quisquam velit est atque accusamus, ratione asperiores maxime dolorem voluptatum temporibus dignissimos culpa laboriosam error neque modi tempora cum? Sed, eveniet?
                Corrupti impedit et inventore architecto repudiandae. Atque facere quam et sequi deleniti, molestias ipsa voluptatem doloribus quae dolore totam quia aspernatur maiores? Eius distinctio eveniet quo eum sunt iusto autem?
                Consectetur culpa labore laboriosam unde! Eum nulla facere atque exercitationem quas harum? Tempora neque tenetur quod, provident sit iste natus impedit dolorum, deserunt ut, rerum ipsam? Delectus tenetur ad quos.
                Mollitia odit sunt quos harum nemo explicabo quasi nulla nesciunt, repellat, sint tempore, aliquid quae sapiente? Praesentium nesciunt, tempore obcaecati voluptate quidem dolorem aperiam veritatis qui, ullam aspernatur et officiis.
                Placeat animi praesentium maxime expedita consequatur tempora recusandae tenetur, aperiam ipsam saepe, dicta a architecto illum pariatur dolorem ducimus cum non impedit officiis asperiores dolor commodi, velit excepturi explicabo. Provident?
                Quo quas fugit quaerat officiis blanditiis laboriosam minus temporibus repudiandae aliquid rem qui excepturi, provident harum facere ipsam. Quae voluptatibus corrupti optio enim corporis sint voluptas illo harum animi laboriosam.
                Ut corrupti exercitationem recusandae? Vitae quasi dolorem ipsam esse eum quo vel quaerat eligendi quis tempore temporibus ad voluptatibus neque nulla, repellendus qui eius beatae deserunt sequi quia repudiandae sint!
                Illo laboriosam explicabo aliquam, hic provident voluptas et labore velit beatae consequuntur ipsa minima. Cumque odio, voluptatibus neque beatae, modi a veritatis voluptates deleniti aperiam quae mollitia sint eaque eveniet.
                Optio omnis expedita natus ratione ipsa totam quo officia placeat cumque incidunt, provident distinctio nam, veniam in explicabo doloribus! At perspiciatis molestiae quidem sapiente ipsa eaque est. Mollitia, ducimus error!
                Repellat consectetur similique a eligendi placeat reprehenderit quam magnam quae laudantium dolor sed voluptate deserunt, quia nihil voluptatibus optio ad iusto repudiandae ipsum aspernatur? Eligendi amet similique adipisci alias sit!
                Atque tempore, corrupti, aspernatur at hic aperiam, dolor commodi dicta possimus facere sint dignissimos impedit id ipsa? Quos unde temporibus nobis, molestiae animi eveniet nam. Minus repellendus tempora doloribus obcaecati.
                Dolorum amet necessitatibus nam labore id, hic eaque nobis quia consectetur quae iure adipisci molestias commodi alias possimus deserunt dolore facilis dolorem quis ipsa maiores quos eius, non praesentium! Fuga?
                Ducimus ipsum distinctio laborum atque incidunt ab laudantium, excepturi quidem magnam dolore eos voluptatibus velit voluptate, dolorem omnis fugit placeat odit qui. Nobis sunt quis illo eius exercitationem placeat reprehenderit.
                Quia aspernatur sequi error tempora explicabo ex nostrum perspiciatis quasi velit praesentium, provident facere soluta ab odit cupiditate delectus dolorem ipsa neque iusto dignissimos voluptate qui odio! Laborum, quae vitae.
                Suscipit doloribus, tenetur doloremque optio numquam, odit a, maxime eum laudantium provident illum aliquam aut magni consequatur obcaecati recusandae. Vel fugiat a distinctio nobis non ratione praesentium qui, culpa iusto!
                Sapiente <strong id="strong">quoququo</strong>quo ullam laudantium excepturi ipsam adipisci quae cumque aperiam omnis voluptatum illo maxime veniam deserunt itaque possimus tempore accusantium, sunt commodi? Ducimus tempora consectetur, aliquam eligendi autem ea commodi.</p>
        </>
    )
}